spring:
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

orion:
  admin:
    email: ${ORION_ADMIN_EMAIL:admin@orion.local}
    password: ${ORION_ADMIN_PASSWORD:admin123*}
